-- ============================================================
-- Consolidated Database Schema for Supabase (PostgreSQL)
-- ============================================================

-- ============================================================
-- ENUM TYPES
-- ============================================================

CREATE TYPE public.publication_type AS ENUM (
    'Journal',
    'Conference',
    'Book Chapter',
    'Proceeding'
);

CREATE TYPE public.gallery_category AS ENUM (
    'Teaching',
    'Research',
    'Community Service',
    'Award',
    'Event'
);

CREATE TYPE public.blog_status AS ENUM ('draft', 'published');

-- ============================================================
-- 1. USERS (Profiles connected to auth.users)
-- ============================================================
CREATE TABLE public.users (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL, -- Managed by Supabase Auth, kept here for schema backward compatibility
    photo VARCHAR(255),
    title VARCHAR(100),
    institution VARCHAR(150),
    biography TEXT,
    social_links JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- 2. EDUCATIONS
-- ============================================================
CREATE TABLE public.educations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
    degree VARCHAR(100),
    major VARCHAR(150),
    institution VARCHAR(150),
    start_year INT,
    end_year INT,
    thesis_title VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- 3. TEACHING
-- ============================================================
CREATE TABLE public.teaching (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
    course_name VARCHAR(150),
    semester VARCHAR(50),
    credits INT,
    description TEXT,
    syllabus_file VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- 4. PUBLICATIONS
-- ============================================================
CREATE TABLE public.publications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
    title VARCHAR(255),
    year INT,
    type public.publication_type DEFAULT 'Journal',
    publisher VARCHAR(255),
    doi VARCHAR(255),
    link VARCHAR(255),
    abstract TEXT,
    authors TEXT,
    cover_image VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- 5. RESEARCH PROJECTS
-- ============================================================
CREATE TABLE public.research_projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
    title VARCHAR(255),
    year_start INT,
    year_end INT,
    funding_source VARCHAR(255),
    role VARCHAR(100),
    abstract TEXT,
    link VARCHAR(255),
    cover_image VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- 6. COMMUNITY SERVICES (Activities)
-- ============================================================
CREATE TABLE public.community_services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
    title VARCHAR(255),
    location VARCHAR(150),
    year INT,
    description TEXT,
    link VARCHAR(255),
    cover_image VARCHAR(255),
    slug VARCHAR(255) UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- 7. AWARDS
-- ============================================================
CREATE TABLE public.awards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
    title VARCHAR(255),
    institution VARCHAR(150),
    year INT,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- 8. PROJECTS
-- ============================================================
CREATE TABLE public.projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
    title VARCHAR(255),
    tech_stack VARCHAR(255),
    description TEXT,
    link VARCHAR(255),
    image VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- 9. GALLERY
-- ============================================================
CREATE TABLE public.gallery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
    category public.gallery_category,
    title VARCHAR(255),
    media_url VARCHAR(255),
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- 10. BLOGS
-- ============================================================
CREATE TABLE public.blogs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) UNIQUE NOT NULL,
    content TEXT NOT NULL,
    tags VARCHAR(255),
    cover_image VARCHAR(255),
    status public.blog_status DEFAULT 'draft',
    views INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Trigger function to update updated_at column
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to run before UPDATE on blogs table
CREATE OR REPLACE TRIGGER on_blogs_update
  BEFORE UPDATE ON public.blogs
  FOR EACH ROW
  EXECUTE PROCEDURE public.handle_updated_at();

-- ============================================================
-- 11. BLOG COMMENTS
-- ============================================================
CREATE TABLE public.blog_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blog_id BIGINT NOT NULL REFERENCES public.blogs (id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100),
    comment TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- 12. CONTACTS
-- ============================================================
CREATE TABLE public.contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    subject TEXT NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- 13. PAGE VIEWS
-- ============================================================
CREATE TABLE public.page_views (
    page_name VARCHAR(100) PRIMARY KEY,
    view_count INT DEFAULT 0,
    last_updated TIMESTAMPTZ DEFAULT NOW()
);
