-- Create the blogs table
CREATE TABLE IF NOT EXISTS blogs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  title TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  content TEXT NOT NULL,
  tags TEXT,
  cover_image TEXT,
  status TEXT DEFAULT 'draft',
  user_id UUID REFERENCES auth.users(id)
);

-- Enable Row Level Security (RLS)
ALTER TABLE blogs ENABLE ROW LEVEL SECURITY;

-- Policy to allow everyone to read published blogs
CREATE POLICY "Enable read access for all users" ON blogs
  FOR SELECT
  USING (status = 'published');

-- Policy to allow authenticated users (admin) to read all blogs (including drafts)
CREATE POLICY "Enable all access for authenticated users" ON blogs
  FOR ALL
  TO authenticated
  USING (true)
  WITH CHECK (true);
