-- Create the contacts table
CREATE TABLE IF NOT EXISTS contacts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  subject TEXT NOT NULL,
  message TEXT NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE contacts ENABLE ROW LEVEL SECURITY;

-- Create policy to allow unrelated inserts (public submission)
-- Anyone can insert, but only admins (if configured) or service_role can read by default if no select policy is added.
CREATE POLICY "Allow public inserts" ON contacts
  FOR INSERT
  WITH CHECK (true);

-- Optional: Create policy to allow reading only by authenticated users (if you have auth setup for admin dashboard)
-- CREATE POLICY "Enable read access for authenticated users only" ON contacts
--   FOR SELECT
--   TO authenticated
--   USING (true);
