-- ============================================================
-- Skrip ini disesuaikan untuk Supabase (PostgreSQL)
-- Tujuan: Menyimpan seluruh aktivitas dan publikasi dosen/peneliti
-- ============================================================

-- ============================================================
-- 1. USERS
-- Catatan: Supabase sudah memiliki tabel `auth.users`.
-- Sebaiknya buat tabel `profiles` yang terhubung ke `auth.users`.
-- Namun, untuk mengikuti struktur asli, tabel `users` dibuat sebagai tabel publik biasa.
-- Pertimbangkan untuk mengintegrasikannya dengan Supabase Auth di masa mendatang.
-- ============================================================
CREATE TABLE public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL, -- Di Supabase, password dikelola oleh Auth, jangan simpan di sini.
    photo VARCHAR(255),
    title VARCHAR(100),
    institution VARCHAR(150),
    biography TEXT,
    social_links JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
-- Aktifkan Row Level Security
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

-- Kebijakan: Izinkan semua orang untuk membaca data profil
CREATE POLICY "Allow public read access to profiles" ON public.users FOR
SELECT USING (true);

-- ============================================================
-- 2. EDUCATIONS
-- ============================================================
CREATE TABLE public.educations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
    degree VARCHAR(100),
    major VARCHAR(150),
    institution VARCHAR(150),
    start_year INT,
    end_year INT,
    thesis_title VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.educations ENABLE ROW LEVEL SECURITY;

-- Kebijakan: Izinkan semua orang untuk membaca data pendidikan
CREATE POLICY "Allow public read access to educations" ON public.educations FOR
SELECT USING (true);

-- ============================================================
-- 3. TEACHING
-- ============================================================
CREATE TABLE public.teaching (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
    course_name VARCHAR(150),
    semester VARCHAR(50),
    credits INT,
    description TEXT,
    syllabus_file VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.teaching ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- 4. PUBLICATIONS
-- ============================================================
CREATE TYPE publication_type AS ENUM (
    'Journal',
    'Conference',
    'Book Chapter',
    'Proceeding'
);

CREATE TABLE public.publications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
    title VARCHAR(255),
    year INT,
    type publication_type DEFAULT 'Journal',
    publisher VARCHAR(255),
    doi VARCHAR(255),
    link VARCHAR(255),
    abstract TEXT,
    authors TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    cover_image VARCHAR(255)
);

ALTER TABLE public.publications ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- 5. RESEARCH PROJECTS
-- ============================================================
CREATE TABLE public.research_projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
    title VARCHAR(255),
    year_start INT,
    year_end INT,
    funding_source VARCHAR(255),
    role VARCHAR(100),
    abstract TEXT,
    link VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    cover_image VARCHAR(255)
);

ALTER TABLE public.research_projects ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- 6. COMMUNITY SERVICES
-- ============================================================
CREATE TABLE public.community_services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
    title VARCHAR(255),
    location VARCHAR(150),
    year INT,
    description TEXT,
    link VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    cover_image VARCHAR(255)
);

ALTER TABLE public.community_services ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- 7. AWARDS
-- ============================================================
CREATE TABLE public.awards (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
    title VARCHAR(255),
    institution VARCHAR(150),
    year INT,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.awards ENABLE ROW LEVEL SECURITY;

-- Kebijakan: Izinkan semua orang untuk membaca data penghargaan
CREATE POLICY "Allow public read access to awards" ON public.awards FOR
SELECT USING (true);

-- ============================================================
-- 8. PROJECTS
-- ============================================================
CREATE TABLE public.projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
    title VARCHAR(255),
    tech_stack VARCHAR(255),
    description TEXT,
    link VARCHAR(255),
    image VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- 9. GALLERY
-- ============================================================
CREATE TYPE gallery_category AS ENUM (
    'Teaching',
    'Research',
    'Community Service',
    'Award',
    'Event'
);

CREATE TABLE public.gallery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
    category gallery_category,
    title VARCHAR(255),
    media_url VARCHAR(255),
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.gallery ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- 10. BLOGS
-- ============================================================
CREATE TYPE blog_status AS ENUM ('draft', 'published');

CREATE TABLE public.blogs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) UNIQUE NOT NULL,
    content TEXT NOT NULL,
    tags VARCHAR(255),
    cover_image VARCHAR(255),
    status blog_status DEFAULT 'draft',
    views INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.blogs ENABLE ROW LEVEL SECURITY;

-- Trigger function untuk memperbarui kolom `updated_at`
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger yang akan dijalankan sebelum UPDATE pada tabel `blogs`
CREATE TRIGGER on_blogs_update
  BEFORE UPDATE ON public.blogs
  FOR EACH ROW
  EXECUTE PROCEDURE public.handle_updated_at();

-- ============================================================
-- 11. BLOG COMMENTS
-- ============================================================
CREATE TABLE public.blog_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blog_id BIGINT NOT NULL REFERENCES public.blogs (id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100),
    comment TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.blog_comments ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- SEEDING DATA (PENGISIAN DATA AWAL)
-- ============================================================

-- ============================================================
-- 1️⃣ USERS
-- ============================================================
INSERT INTO
    public.users (
        name,
        email,
        password,
        photo,
        title,
        institution,
        biography,
        social_links
    )
VALUES (
        'M. Taufiq,M.Kom',
        'mtaufiq39@gmail.com',
        md5('password123'), -- Peringatan: Ini hanya untuk contoh. Gunakan Supabase Auth untuk manajemen password yang aman.
        '/profile.jpg',
        'Asisten Ahli',
        'Sekolah Tinggi Ilmu Komputer Banyuwangi',
        'Dosen dan peneliti di bidang pengembangan perangkat lunak, kecerdasan buatan, dan sistem informasi. Aktif melakukan penelitian dan pengabdian masyarakat berbasis digitalisasi pendidikan.',
        jsonb_build_object (
            'google_scholar',
            'https://scholar.google.com/citations?user=IuAv028AAAAJ&hl=id',
            'orcid',
            'https://orcid.org/0000-0003-3473-7847',
            'sinta',
            'https://sinta.kemdiktisaintek.go.id/authors/profile/6000762',
            'linkedin',
            'https://linkedin.com/in/limfiq',
            'github',
            'https://github.com/limfiq'
        )
    );

-- ============================================================
-- 2️⃣ EDUCATIONS
-- ============================================================
INSERT INTO
    public.educations (
        user_id,
        degree,
        major,
        institution,
        start_year,
        end_year,
        thesis_title
    )
VALUES (
        1,
        'S1',
        'Teknik Informatika',
        'Sekolah Tinggi Ilmu Komputer PGRI Banyuwangi',
        2009,
        2012,
        'Sistem Informasi data siswa dengan Java dan MySQL'
    ),
    (
        1,
        'S2',
        'Teknologi Informasi',
        'Universitas Dian Nuswantoro',
        2014,
        2016,
        'Implementasi Neural Network untuk Klasifikasi Data Pendidikan'
    ),
    (
        1,
        'S3',
        'Ilmu Komputer',
        'Universitas Gadjah Mada',
        2017,
        2021,
        'Optimasi Deep Learning untuk Deteksi Citra Pertanian'
    );

-- ============================================================
-- 3️⃣ TEACHING
-- ============================================================
INSERT INTO
    public.teaching (
        user_id,
        course_name,
        semester,
        credits,
        description,
        syllabus_file
    )
VALUES (
        1,
        'Pengembangan Backend',
        'Ganjil 2024/2025',
        3,
        'Mata kuliah ini membahas dasar hingga lanjut pengembangan backend menggunakan Express.js dan MySQL.',
        'https://example.com/files/syllabus-backend.pdf'
    ),
    (
        1,
        'Software Quality Assurance',
        'Genap 2024/2025',
        4,
        'Mata kuliah ini mempelajari penerapan standar kualitas perangkat lunak (ISO/IEC 25010) dan praktik pengujian perangkat lunak.',
        'https://example.com/files/syllabus-sqa.pdf'
    );

-- ============================================================
-- 4️⃣ PUBLICATIONS
-- ============================================================
INSERT INTO
    public.publications (
        user_id,
        title,
        year,
        type,
        publisher,
        doi,
        link,
        abstract,
        authors
    )
VALUES (
        1,
        'Machine Learning-based Model for Predicting Student Performance',
        2023,
        'Journal',
        'International Journal of Computer Science',
        '10.1234/ijcs.2023.001',
        'https://journal.org/article/1234',
        'This study develops an ML model to predict academic performance using behavioral data.',
        'Limfiq, R. A., Suryono, T.'
    ),
    (
        1,
        'Digital Transformation of Mosque Management System',
        2022,
        'Conference',
        'ICITEE Conference',
        '10.5678/icitee.2022.008',
        'https://conference.org/paper/5678',
        'A digitalization model for mosque management using cloud-based information systems.',
        'Limfiq, M., Hidayat, A.'
    );

-- ============================================================
-- 5️⃣ RESEARCH PROJECTS
-- ============================================================
INSERT INTO
    public.research_projects (
        user_id,
        title,
        year_start,
        year_end,
        funding_source,
        role,
        abstract,
        link
    )
VALUES (
        1,
        'Penerapan Kecerdasan Buatan untuk Identifikasi Tanaman Sakit',
        2023,
        2025,
        'DRPM Kemendikbud',
        'Ketua',
        'Penelitian ini mengembangkan model computer vision berbasis CNN untuk mendeteksi penyakit tanaman padi.',
        'https://example.com/research/ai-pertanian'
    ),
    (
        1,
        'Digitalisasi Sistem Presensi Siswa dan Guru di Madrasah',
        2024,
        2024,
        'Internal',
        'Ketua',
        'Membangun aplikasi presensi digital berbasis QR code menggunakan AppSheet dan Supabase.',
        'https://example.com/research/presensi-digital'
    );

-- ============================================================
-- 6️⃣ COMMUNITY SERVICES
-- ============================================================
INSERT INTO
    public.community_services (
        user_id,
        title,
        location,
        year,
        description,
        link
    )
VALUES (
        1,
        'Pelatihan Pengelolaan Data Digital untuk Takmir Masjid',
        'Desa Tukangkayu, Banyuwangi',
        2024,
        'Kegiatan pengabdian untuk meningkatkan kemampuan pengurus masjid dalam manajemen data digital dan administrasi.',
        'https://example.com/community/masjid-digital'
    ),
    (
        1,
        'Workshop Literasi Digital bagi Guru MI',
        'MI Darul Ulum Grogol',
        2025,
        'Pengabdian dalam bentuk pelatihan digitalisasi absensi guru dan siswa menggunakan aplikasi AppSheet.',
        'https://example.com/community/mi-digital'
    );

-- ============================================================
-- 7️⃣ AWARDS
-- ============================================================
INSERT INTO
    public.awards (
        user_id,
        title,
        institution,
        year,
        description
    )
VALUES (
        1,
        'Best Paper Award',
        'ICITEE Conference',
        2023,
        'Penghargaan atas kontribusi penelitian bidang sistem informasi pendidikan.'
    ),
    (
        1,
        'Dosen Berprestasi 1',
        'Sekolah Tinggi Ilmu Komputer Banyuwangi',
        2024,
        'Penghargaan atas inovasi dan publikasi penelitian.'
    );

-- ============================================================
-- 8️⃣ PROJECTS
-- ============================================================
INSERT INTO
    public.projects (
        user_id,
        title,
        tech_stack,
        description,
        link,
        image
    )
VALUES (
        1,
        'Sistem Presensi Digital MI Darul Ulum',
        'AppSheet, Supabase, Canva',
        'Aplikasi digitalisasi presensi siswa dan guru berbasis QR Code.',
        'https://example.com/projects/presensi',
        'https://example.com/images/project-presensi.png'
    ),
    (
        1,
        'Website Portofolio Dosen & Peneliti',
        'Next.js, Supabase, TailwindCSS',
        'Platform personal branding dosen untuk publikasi kegiatan akademik dan penelitian.',
        'https://example.com/projects/portfolio',
        'https://example.com/images/project-portfolio.png'
    );

-- ============================================================
-- 9️⃣ GALLERY
-- ============================================================
INSERT INTO
    public.gallery (
        user_id,
        category,
        title,
        media_url,
        description
    )
VALUES (
        1,
        'Teaching',
        'Praktikum Express.js Mahasiswa TI',
        'https://example.com/gallery/express-class.jpg',
        'Kegiatan pembelajaran backend development menggunakan Node.js dan Express.'
    ),
    (
        1,
        'Community Service',
        'Digitalisasi Manajemen Masjid',
        'https://example.com/gallery/masjid-digital.jpg',
        'Kegiatan pengabdian untuk mendigitalisasi administrasi masjid di Banyuwangi.'
    );

-- ============================================================
-- 🔟 BLOGS
-- ============================================================
INSERT INTO
    public.blogs (
        user_id,
        title,
        slug,
        content,
        tags,
        cover_image,
        status,
        views
    )
VALUES (
        1,
        'Mengapa Dosen Harus Punya Portofolio Digital?',
        'mengapa-dosen-harus-punya-portofolio-digital',
        'Di era akademik modern, portofolio digital bukan hanya tempat pamer karya, tetapi juga bentuk transparansi dan branding profesional dosen. Dalam tulisan ini, saya berbagi pengalaman membangun website portofolio menggunakan Next.js dan Supabase...',
        'Pendidikan, Teknologi, Dosen',
        'https://example.com/images/blog-portfolio.jpg',
        'published',
        102
    ),
    (
        1,
        'Membangun Budaya Penelitian di Kampus Swasta',
        'membangun-budaya-penelitian-di-kampus-swasta',
        'Meningkatkan budaya penelitian di kampus swasta membutuhkan sinergi antara pimpinan, dosen, dan mahasiswa. Artikel ini membahas strategi praktis berbasis pengalaman di lapangan...',
        'Penelitian, Pendidikan, Akademik',
        'https://example.com/images/blog-research.jpg',
        'published',
        87
    );

-- ============================================================
-- 1️⃣1️⃣ BLOG COMMENTS
-- ============================================================
INSERT INTO
    public.blog_comments (blog_id, name, email, comment)
VALUES (
        1,
        'Andi Saputra',
        'andi@gmail.com',
        'Tulisan yang sangat menginspirasi Pak, saya tertarik membuat portofolio serupa.'
    ),
    (
        2,
        'Rina Kusuma',
        'rina@stikom.edu',
        'Terima kasih atas pandangannya, Pak. Sangat relevan untuk kampus kami.'
    );

-- ============================================================
-- ✅ SKRIP SELESAI
-- ============================================================